name: Pipravi podatke


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Poskrbi, da bo uporabljena verzija, združljiva s TensorFlow 2.10.1

    - name: Run pobrisi gitignore
      run: |
        git config user.name "Benjamin"
        git config user.email "benjamin.petelinek@gmail.com"
        
        echo " " > data/processed/.gitignore
        git add data/processed/.gitignore
        git commit -m "Clean .gitignore"
        git push
        
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        dvc remote modify origin --local access_key_id 30663408e580bdb3f66e074627577a040f36b5ff
        dvc remote modify origin --local secret_access_key 30663408e580bdb3f66e074627577a040f36b5ff

        
        dvc pull -r origin --force


    

    - name: Run izprazni.py
      run: |
        python notebooks/Projekt/izprazni.py
        git add .
        git commit -m "Update changes"
        git push
    
    - name: Run fetch_data_nesrece.py
      run: |
        python notebooks/Projekt/pridobi_nesrece.py
        

    - name: Run fetch_data_promet.py
      run: |
        python notebooks/Projekt/prodobi_prometne_podatke.py
        

    - name: Run fetch_data_vreme.py
      run: |
        python notebooks/Projekt/pridobi_vremenske_podatke.py
        git add .
        git commit -m "Update changes"
        git push

        

    - name: Run pre_process.py
      run: |
        python notebooks/Projekt/pre_process.py
        git add .
        git commit -m "Update changes"
        git push
        

    - name: Run GreatExpectations
      run: |
        python notebooks/Projekt/GreatExp.py
        git add .
        git commit -m "Update changes"
        git push

    - name: Run Evidently
      run: |
        python notebooks/Projekt/evi_script.py
        git add .
        git commit -m "Update changes"
        git push

    - name: Run current.py
      run: |
        python notebooks/Projekt/ustvari_current.py

        git rm -r --cached 'data/processed/current_data.csv'
        git rm -r --cached 'data/processed/reference_data.csv'
        git commit -m "stop tracking data/processed/current_data.csv"

        
           

    
    - name: Run razdeli
      run: |
        python notebooks/Projekt/train_test_split.py

        dvc add "data/processed/current_data.csv"
        dvc add "data/processed/reference_data.csv"

        dvc push -r origin
        git add .
        git commit -m "Update changes"
        git push
        
    
       
        
        

    
    
    


    
