name: grajenje in ovrednotenje modela

on:
  workflow_run:
    workflows: ["Pipravi podatke"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Poskrbi, da bo uporabljena verzija, združljiva s TensorFlow 2.10.1

    - name: Install dependencies
      run: |
        git config user.name "Benjamin"
        git config user.email "benjamin.petelinek@gmail.com"
        python -m pip install --upgrade pip
        pip install -r requirements.txt
